CREATE SEQUENCE seq_video_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_imagen_id START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pdf_id START WITH 1 INCREMENT BY 1;


DROP SEQUENCE seq_video_id;
DROP SEQUENCE seq_imagen_id;
DROP SEQUENCE seq_pdf_id;
